---
- name: Create Directory
  hosts: 172.16.0.236
  become: yes
  tasks:
    - name: Create a directory
      file:
        path: /home/divya/test1
        state: directory
        owner: divya
        group: divya
        mode: 0755
