---
- hosts: 172.16.0.120
  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Configure Nginx
    lineinfile:
      path: /etc/nginx/sites-available/default
      line: server {
            listen 80;
            server_name localhost;
            location / {
                root /usr/share/nginx/html;
            }
          }
      state: present

  - name: Restart Nginx
    service:
      name: nginx
      state: restarted

