---
- name: Install Nginx
  hosts: 172.16.0.120  # Replace 'your_target_host' with the actual host or group name
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      retries: 5
      delay: 10
