---
- name: Install Nginx on Ubuntu
  hosts: 172.16.0.120
  become: yes  # This is required to run commands with root privileges

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: yes

