---
- name: Create Folder in Windows
  hosts: 10.10.5.181  # Replace 'windows_hosts' with the name of your Windows host group or individual host.
  gather_facts: false
  tasks:
    - name: Create Folder
      win_file:
        path: C:\\Windows\\ansible-testing  # Specify the path to the folder you want to create.
        state: directory
